apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-workshop
  version: "1.25"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

managedNodeGroups:
  - name: c5-9xl
    instanceType: c5.9xlarge
    instancePrefix: c5-9xl
    privateNetworking: true
    availabilityZones: ["us-east-1a","us-east-1b"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
