apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-karpenter-efa
  version: "1.22"
  region: us-east-1
  tags:
    karpenter.sh/discovery: do-eks-yaml-karpenter-efa

availabilityZones:
  - us-east-1a
  - us-east-1b

managedNodeGroups:
  - name: c5-xl-do-eks-karpenter-ng
    instanceType: c5.xlarge
    instancePrefix: c5-xl
    privateNetworking: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true
  
  - name: g4dn-8xl
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn-8xl
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
