apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-karpenter-dev
  version: "1.25"
  region: us-east-1
  tags:
    karpenter.sh/discovery: do-eks-yaml-karpenter-dev

managedNodeGroups:
  - name: c5-xl-eks-karpenter-dev-ng
    instanceType: t3.medium
    instancePrefix: c5-xl
    privateNetworking: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true

iam:
  withOIDC: true
