apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-gpu
  version: "1.25"
  region: us-east-1
  tags:
    karpenter.sh/discovery: do-eks-yaml-gpu

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true
 
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn
    privateNetworking: true
    efaEnabled: false
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true

  - name: p3dn
    instanceType: p3dn.24xlarge
    instancePrefix: p3dn
    privateNetworking: true
    efaEnabled: false
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true

iam:
  withOIDC: true
