---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: do-eks-yaml-minimal
  region: us-east-1
  version: "1.21"
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  iam:
    withAddonPolicies:
      albIngress: true
