# spot-cluster.yaml
# Reference: https://eksctl.io/usage/spot-instances/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-spot
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: ["c3.large","c4.large","c5.large","c5d.large","c5n.large","c5a.large","m5.large"]
  spot: true
