# Reference: https://eksctl.io/usage/eksctl-karpenter/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-yaml-karpenter
  version: "1.28"
  region: us-east-1
  tags:
    karpenter.sh/discovery: do-eks-yaml-karpenter

iam:
  withOIDC: true

karpenter:
  version: 'v0.31.0'
  createServiceAccount: true
  #  defaultInstanceProfile: 'KarpenterInstanceProfile'

managedNodeGroups:
  - name: c5-xl-do-eks-karpenter-ng
    instanceType: t3.medium
    instancePrefix: c5-xl
    privateNetworking: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 300
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true
